import pandas as pd

# Sample data as an array
data  = [
        {
            "title": "Save on Cartridge Plus | Business for Sale",
            "overview": "Since 2003, Save on Cartridges provides solutions to make your business more convenient, from ink refills to package delivery to referrals and design. An established brand with a mature operating system serving all of BC and across Canada. Business provides ink refill/toner cartridge/printer services, Mailboxes, access point for UPS, FEDEX, CANPAR, SPRINTSTAR, AMAZON, LANDMARK, APPLE EXPRESS, PUDO, WISH, ALIBABA AND SHINE,UNI UNI, Neighbor Express, Bounce, Forwarding Mail. MailBox Service. Along with phone/electronic/printing services and all graphic design needs etc. *Potential service to add for new buyer: money transfer* \n\n600 sqft available working space, water connection, flexible store layout, very reasonable rent ($2,500/monthly/negotiable), conveniently located on busy E Hastings street, high exposure and heavy foot traffic area. Close to all amenities, free parking, friendly neighbours, lots of walk-in traffic. Great location with the potential for growth and success. \n\nSale price includes training, goodwill, inventory and equipment required for operation. Act swiftly to secure your place at the helm of this opportunity!",
            "industry": "Repair/Maintenance Services",
            "price": "$137,000",
            "currency": "CAD",
            "created_timestamp": "1694126056",
            "created_datetime": "2023-09-07T18:34:16-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Vancouver",
            "province": "BC",
            "country": "Canada",
            "location": "Vancouver, BC, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6366",
            "url": "https://buyandsellabusiness.com/business-opportunities/3623/save-on-cartridge-plus-business-for-sale"
        },
        {
            "title": "Specialty Equipment Distributor and Services Business",
            "overview": "This 30 year old niche equipment supplier and specialty service business will be an ideal fit for you if you are passionate about solving problems and truly serving customers. Or, perhaps you&#039;ve already found a foothold in business and are ready for a roll-up to take advantage of the leverage opportunities that exist.\n\nSituated in a thriving industry that will be around for decades to come, once you become the owner of this well known, well established, highly reputed operation, we&#039;re confident you&#039;ll find many additional ways to enhance your life beyond just the daily responsibilities and commitments.\n\n- seller&#039;s reason for sale is retirement, willing to provide necessary support to ensure a successful transition. Currently working minimal time &quot;in&quot; the business\n- much effort has been invested to ensure policies and procedures are in place\n- web-site, google rankings, and SEO all updated and in great position\n- solid management team in place\n- many service contracts in place to support repeat revenues\n\nThe sale is structured as a sale of 100% of the authorized and issued share capital of the company. Working Capital shall be adjusted at $0.",
            "industry": "Distribution",
            "price": "$1,329,000",
            "currency": "CAD",
            "created_timestamp": "1694117803",
            "created_datetime": "2023-09-07T16:16:43-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Confidential",
            "province": "NS",
            "country": "Canada",
            "location": "Confidential, NS, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6365",
            "url": "https://buyandsellabusiness.com/business-opportunities/3622/specialty-equipment-distributor-and-services-business"
        },
        {
            "title": "Longstanding Electrical Services Company with Real Estate",
            "overview": "Electrical contractor focused on commercial, residential, new construction and renovation, along with other power supply services.\n\n55 year old operation, selling for retirement purposes.\n- approximately 20 staff\n- owned building\n- 10 vehicles\n- Excellent upside with tighter controls. Only 1 price increase in 5 years, simple example. Many other to share.\n\nThe sale is structured as a sale of 100% of the authorized and issued share capital of the company. For the purposes of this offering, the price considers Working Capital of $100,000 to be included. By completing the NDA and becoming a qualified buyer, we&#039;ll be happy to send you a full Offering Memorandum that will answer most, if not all, of your questions once the listing is live.\n\n\nFINANCIAL INFORMATION\nHistorical Annual Revenues and Seller&#039;s Discretionary Earnings:\n*Fiscal year-end is July 31.\n\n2024 Projection\nRevenue: $2,000,000 (first price increase in 5 years implemented in Summer &#039;23)\n\n2023\nRevenue: $1,907,000\nSDE: $ in progress, expected to be approximately $250k\n\n2022\nRevenue: $1,629,000\nSDE: $164k\n\n2021\nRevenue: $1,532,000\nSDE: $242k",
            "industry": "Construction Services",
            "price": "$1,459,000",
            "currency": "CAD",
            "created_timestamp": "1694027732",
            "created_datetime": "2023-09-06T15:15:32-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Confidential",
            "province": "NS",
            "country": "Canada",
            "location": "Confidential, NS, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6364",
            "url": "https://buyandsellabusiness.com/business-opportunities/3621/longstanding-electrical-services-company-with-real-estate"
        },
        {
            "title": "Road Construction Contracting Business FOR SALE",
            "overview": "- A Profitable and very well-established Road Construction Contracting company that has been active mainly in Southwestern Ontario for approx. 21 years.\n\n- Business services the commercial, industrial, municipal, institutional and residential sectors, with revenues earned primarily from projects.\n\n- Business has built an excellent reputation for providing superior full-service package to its clients, with high attention to safety, quality work and timely delivery of projects; thus, becoming the go-to solution provider for road construction in its covered territory.\n\n- A team driven business with a reputation of quality and professionalism that stands out in every completed project, while meeting and exceeding the quality standards.\n\n- The Companys highly skilled workforce is the dynamic driver of its excellent reputation and success.\n\n- Company has a multi-year track record of profitability with average revenue exceeding $8M and discretionary earnings approx. $700K during the last 4 financial years.\n\n- Business has developed a strong relationship with their loyal client base, benefiting from regular repeat business and referrals.",
            "industry": "Construction Services",
            "price": "$3,500,000",
            "currency": "CAD",
            "created_timestamp": "1693940514",
            "created_datetime": "2023-09-05T15:01:54-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Southwestern Ontario",
            "province": "ON",
            "country": "Canada",
            "location": "Southwestern Ontario, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3620/road-construction-contracting-business-for-sale"
        },
        {
            "title": "High-End Stairs Manufacturing Business FOR SALE",
            "overview": "- Elite Craftsmanship: This business specializes in custom high-end stairs and railing. Each design is a testament to unique architecture and unmatched artistic craftsmanship, tailoring to an elite clientele.\n\n- Robust Profitability: Achieving annual sales of approx. $1.3M and Seller&#039;s Discretionary Earnings of an impressive $642K for 2022.\n\n- Impressive Margin: The business&#039;s operational model and efficiency lead to an outstanding profit margin, suggesting excellent potential returns for the future buyer.\n\n- Valuable Assets: The business comes with approx. $302K worth of fully paid equipment, significantly adding to its value. Equipment includes machinery, truck, and van assets fully paid off, ensuring the incoming owner commences with no equipment-related debts.\n\n- Volume &amp; Value: Annually, the business manages 300-400 jobs, indicative of its consistent demand and market presence.\n\n- Stable Income Stream: 75% of the revenue is recurring, assuring a continuous cash flow.\n\n- Versatile Project Range: From compact projects starting at $3-4K to grand projects worth $200K.",
            "industry": "Construction Services",
            "price": "$1,650,000",
            "currency": "CAD",
            "created_timestamp": "1693940378",
            "created_datetime": "2023-09-05T14:59:38-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Southern Ontario",
            "province": "ON",
            "country": "Canada",
            "location": "Southern Ontario, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3619/high-end-stairs-manufacturing-business-for-sale"
        },
        {
            "title": "Roofing Business FOR SALE in Halifax",
            "overview": "- Established Legacy: With a rich history dating back to 1980s, this business has built a solid reputation in the roofing industry.\n\n- Impressive Financials: 2022 Year-End revenue boasted a remarkable figure close to $1 million, showcasing the business&#039;s thriving success.\n\n- Solid Earnings: With a Seller&#039;s Discretionary Earnings (SDE) of $232k in 2022, it&#039;s evidence of both profitability and potential for further growth.\n\n- Stellar Reputation: Trusted by the Halifax community for unmatched service and quality.\n\n- Word-of-Mouth Powerhouse: A high percentage of the business is driven by enthusiastic referrals from satisfied customers.\n - Confidence Guaranteed: Business offers an unmatched lifetime warranty on materials and a 10-year labor warranty. The business stands by its work, which translates to happy and repeat customers.\n\n- Covering Halifax and Beyond: Serving the entire metro Halifax area and its beautiful surroundings.\n\n- Year-Round Excellence: Rain or shine, snow or sleet; the business is on the job throughout the four seasons.\n\n- Strong Contractor Network: With a dedicated team of 12 contractors, every project receives the expert touch.",
            "industry": "Construction Services",
            "price": "$600,000",
            "currency": "CAD",
            "created_timestamp": "1693939873",
            "created_datetime": "2023-09-05T14:51:13-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Halifax",
            "province": "NS",
            "country": "Canada",
            "location": "Halifax, NS, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3618/roofing-business-for-sale-in-halifax"
        },
        {
            "title": "Niche General Contracting Business FOR SALE in Surrey",
            "overview": "-  Turnkey Opportunity: Step into a fully operational business model with all the latest systems in place, ensuring a seamless start for the new owner.\n\n- Over a Decade of Excellence: Profitable, licensed, and bonded Commercial General Contracting and Custom Home Building business, thriving for 12 years in Mainland B.C.\n\n- Impressive Financials: Boasting an average yearly revenue of over $5 million for the past 4 years.\n\n- Proven Profitability: Fiscal 2023 showcased normalized seller discretionary earnings exceeding $431,000.\n\n- Unique Market Position: Specialization in renovating multi-residential suites and crafting custom homes, serving primarily BC market, with a presence in ON. Offering an opportunity for a visionary to expand nationally.\n\n- Organic Client Growth: Largely referral-based clientele with a significant proportion of repeat customers underlining trust.\n\n- Quality at its Best: Reputation for outstanding quality, professionalism, and efficiency, consistently exceeding quality standards with each project.\n\n-  Customer Satisfaction: Recognized as the go-to general contracting company in the region, attributed to impeccable customer service.",
            "industry": "Construction Services",
            "price": "$1,049,000",
            "currency": "CAD",
            "created_timestamp": "1693939228",
            "created_datetime": "2023-09-05T14:40:28-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Surrey",
            "province": "BC",
            "country": "Canada",
            "location": "Surrey, BC, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3617/niche-general-contracting-business-for-sale-in-surrey"
        },
        {
            "title": "Successful Electric motor shop for sale in North Carolina.",
            "overview": "Electric motor shop for sale in North Carolina. Company repair and sales electric motors and pumps. Great opportunity to get a long established business. Owner will stay up to 6 months post sell",
            "industry": "Repair/Maintenance Services",
            "price": "$500,000",
            "currency": "USD",
            "created_timestamp": "1693863653",
            "created_datetime": "2023-09-04T17:40:53-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Charlotte",
            "province": "NC",
            "country": "United States",
            "location": "Charlotte, NC, United States",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6362",
            "url": "https://buyandsellabusiness.com/business-opportunities/3616/successful-electric-motor-shop-for-sale-in-north-carolina"
        },
        {
            "title": "Seasonal Cottage Rental",
            "overview": "Located in one of the most frequented and beloved destinations of Nova Scotia, alongside a National Park, this 13-unit cottage rental business has been well cared for, is up to date, and has received a top tier reputation from its customers that supports a strong future for the new owner.\n\nBeing located next to a National Park means many things. Consistency and beauty are two things that easily come to mind. Not only is there much upside available to increase profits and value, the lifestyle to be enjoyed is one of the finest in Nova Scotia if you appreciate incredible beauty and the outdoors.\n\nA few highlights to give you some additional insight on the current status and future opportunity:\n1. Two cabins have not been rented for several years and could add an additional $50k to the top-line. The larger of the two cabins would fetch $250/night or more if you were to not use it for owner&#039;s accommodations. Other owner accommodation solutions exist, let&#039;s talk.\n2. Operating season can be extended by 3 or 4 weeks, which would add approximately $30k.\n3. There is land to easily add 3 more cabins today, or you could add 7 more cabins if additional land were to be acquired from the seller.",
            "industry": "Real Estate",
            "price": "$1,249,000",
            "currency": "CAD",
            "created_timestamp": "1693847130",
            "created_datetime": "2023-09-04T13:05:30-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Confidential",
            "province": "NS",
            "country": "Canada",
            "location": "Confidential, NS, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6361",
            "url": "https://buyandsellabusiness.com/business-opportunities/3615/seasonal-cottage-rental"
        },
        {
            "title": "Cheticamp Outback Inn",
            "overview": "Cheticamp Outback Inn is newly renovated and offers the whole package. It&#039;s perfect for new owners looking for some freedom to explore and enjoy the beauty of being just a few minutes from one of &quot;Canada&#039;s Seven Wonders&quot;, the Cabot Trail. The inn is perfectly located near amenities, beaches and world famous hiking trails.\n\nThis package boasts a brand new two-bedroom owner&#039;s suite and four queen suites with kitchenettes. They are booked nearly year round, and it&#039;s no surprise given the 2023 Traveller Review Awards and 5-star rating across the board.\n\nThe sale is structured as a sale of 100% of the authorized and issued share capital of the company. Working Capital shall be adjusted at $0. By completing the NDA and becoming a qualified buyer, we&#039;ll be happy to send you a full Offering Memorandum that will answer most of your questions.\n\nFINANCIAL INFORMATION\nAnnual Revenue and Seller&#039;s Discretionary Earnings\n2022\nRevenue: $155,000\nSDE: $105,000\n\n2021\nRevenue: $86,000\nSDE: $53,000\n\n2020\nRevenue: $140,000\nSDE: $80,000",
            "industry": "Real Estate",
            "price": "$489,000",
            "currency": "CAD",
            "created_timestamp": "1693846380",
            "created_datetime": "2023-09-04T12:53:00-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Confidential",
            "province": "NS",
            "country": "Canada",
            "location": "Confidential, NS, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6360",
            "url": "https://buyandsellabusiness.com/business-opportunities/3614/cheticamp-outback-inn"
        },
        {
            "title": "Ice Manufacturing Business, Large cocktail format ice",
            "overview": "Break The Ice AZ is a local ice manufacturing company. We sell to restaurants and bars throughout the valley in the Phoenix area. We have over 40 steady business accounts and we have a lot more accounts interested in getting becoming our clients, but we are limited on expansion due to our resources. There is a ton of growth opportunity in this business and you can easily expand to a million in gross sales in 2 to 3 years with the right financial resources. \n\nThe net profit on this business is a great percentage as well. We have been putting so much money back into the business and paying off original debts to launch the business, and we still have around a 30% return. This business can easily get you a 40% net return when operating at full capacity and having the right financial backing.\n\nWe are projected to do around $275,000 plus for our third year in business and we will have a 63% growth from our second year to third year. We had a 231% growth from our first year to our second year in business. \n\nThere&#039;s also over $80,000 in equipment equity in our business. \n\nWe would love to share with you all of our information if you are interested. Please don&#039;t hesitate to reach out to us.",
            "industry": "Manufacturing",
            "price": "$300,000",
            "currency": "USD",
            "created_timestamp": "1693622914",
            "created_datetime": "2023-09-01T22:48:34-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Gilbert",
            "province": "AZ",
            "country": "United States",
            "location": "Gilbert, AZ, United States",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6359",
            "url": "https://buyandsellabusiness.com/business-opportunities/3613/ice-manufacturing-business-large-cocktail-format-ice"
        },
        {
            "title": "Lucrative Convenience Store with Bakery including Real Estate",
            "overview": "Situated in a bustling neighborhood with high foot traffic, this business comprises of convenience store, bakery, bar with VLT, and 4 rental apartment units. The business has demonstrated consistent profitability, with strong revenue and healthy profit margins.\n\nThis is an exceptional opportunity to acquire a well-established brew and convenience store with a loyal customer base, prime location, and solid financial performance. Whether you are an experienced business owner in the retail industry or an entrepreneur looking to enter this thriving market, this business offers both stability and growth potential.\n\nDon&#039;t miss out on the chance to own a successful business. Contact us today to learn more about this remarkable opportunity, schedule a private showing, and take the first step toward a rewarding and profitable business venture.\n\nThe sale is structured as an Asset sale. Working Capital shall be adjusted at $0. By completing the NDA and becoming a qualified buyer, we&#039;ll be happy to send you a full Offering Memorandum that will answer most of your questions.",
            "industry": "Convenience/Variety Store",
            "price": "$1,050,000",
            "currency": "CAD",
            "created_timestamp": "1693590697",
            "created_datetime": "2023-09-01T13:51:37-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Confidential",
            "province": "NB",
            "country": "Canada",
            "location": "Confidential, NB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6358",
            "url": "https://buyandsellabusiness.com/business-opportunities/3612/lucrative-convenience-store-with-bakery-including-real-estate"
        },
        {
            "title": "All-in-One Full Service 138-Room Hotel, Restaurant and Liquor",
            "overview": "For sale is a well-maintained, full service, non-franchised hotel that consists of 138 rooms: main building, 67; lodge, 35; other, 36.\nThe total number of rooms with kitchenettes are 60, 18 of which are occupied full-time by long-term emergency medical &amp; safety crews. In this town, kitchenettes are on high demand. This business has several advantages as it operates in a high traffic area.\n\nIncluded in the business are:\n- Leased restaurant, lounge (with 4 VLTs) and liquor store.\n- Coin laundry (with 7 washers and 8 dryers) with an income of $50,000/year.\n\n\nFINANCIAL INFORMATION\nAnnual Revenues and Net Operating Income:\n2022 (accounting for 11 months YTD financials)\nRevenue: $4,183,725\nNOI: $1,675,395\n\n2021\nRevenue: $3,246,089\nNOI: $1,439,978\n\n2020\nRevenue: $1,515,299\n\n2019\nRevenue: $2,496,828\nNOI: $675,934\n\nREAL ESTATE\nLease details:\nRestaurant&#039;s lease is at $300,000 including utilities and will be renewed in 2023 for another 5 years. The rent fee will go up when the number of VLTs increases and one more VLT is expected in 2023.\nLiquor store&#039;s lease is at $60,000 including utilities and the term is until 2024.\n\nAll furniture, fixtures and equipment are owned by the landlord.",
            "industry": "Hospitality",
            "price": "$13,950,000",
            "currency": "CAD",
            "created_timestamp": "1693395961",
            "created_datetime": "2023-08-30T07:46:01-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Confidential",
            "province": "AB",
            "country": "Canada",
            "location": "Confidential, AB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6357",
            "url": "https://buyandsellabusiness.com/business-opportunities/3611/all-in-one-full-service-138-room-hotel-restaurant-and-liquor"
        },
        {
            "title": "Commercial/Residential Recycling Business For Sale",
            "overview": "Pre approved for financing and seller financing available as well.\n\n45% SDE\n\nHigh % of business comes from contracted revenue.\n\nApprox $475,000 in assets and inventory included in selling price.\n\nSince 2006, offering a wide range of recycling services, from paper and plastics to household paints and more. They offer unique and efficient recycling solutions that attract both environmentally conscious consumers and businesses.\n\n3 processing facilities with one being the largest recycling facility in Northwestern BC.\n\nHuge economic growth right now. The recycling industry is on the rise, and this business is perfectly positioned to scale to new heights.\n\nFully trained staff with full time manager in place. Owner does some admin work remotely and visits facility every 6 - 8 weeks.\n\nReceive comprehensive training and support by the current owner to ensure a smooth handover and a\nsuccessful business journey.\n\nSerious inquiries only. To learn more about this exciting opportunity and to receive detailed financials, contact us.",
            "industry": "Environmental Services",
            "price": "$2,399,000",
            "currency": "CAD",
            "created_timestamp": "1693273081",
            "created_datetime": "2023-08-28T21:38:01-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Terrace",
            "province": "BC",
            "country": "Canada",
            "location": "Terrace, BC, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6356",
            "url": "https://buyandsellabusiness.com/business-opportunities/3610/commercial-residential-recycling-business-for-sale"
        },
        {
            "title": "Well Established and Respected Roofing Business For Sale",
            "overview": "From repairs and replacements to installations and renovations, this business boasts a diverse range of roofing services that cater to various client needs.\n\nThey are well established with 17 years in the business and have built a stellar reputation with their clients, suppliers and within the roofing industry.\n\nHighly profitable with many streams of revenue including a 2/3 of the companys revenues are generated from established relationships with local custom homebuilders &amp; general contractors that provide them with plenty of work every year.\n\nBoth owners are very well known &amp; respected in the industry and one of them has extensive relationships in the industry and is a well-respected industry leader: \n\nExperienced team in place including skilled roofers and efficient project management team.\n\nThey are at the forefront of roofing trends and technologies. Roofing quotes are done with a drone and high-end technology to give the best solution to the client and ensure safety for all involved.\n\nGreat relationship with suppliers and long-term accounts in place.\n\nCOR safety certified,\n\nThe current owners have targeted future growth opportunities that they will assist the new owners.",
            "industry": "Construction Services",
            "price": "$1,135,418",
            "currency": "CAD",
            "created_timestamp": "1693271999",
            "created_datetime": "2023-08-28T21:19:59-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Calgary",
            "province": "AB",
            "country": "Canada",
            "location": "Calgary, AB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6355",
            "url": "https://buyandsellabusiness.com/business-opportunities/3609/well-established-and-respected-roofing-business-for-sale"
        },
        {
            "title": "Beautiful 200-Site Waterfront Campground on 24 Acres",
            "overview": "Located in one of the most beautiful areas of the province, heavily frequented by tourists, and many wonderful options to live a great life outdoors, this campground has been the victim of many updates and upgrades over the last few years, that has positioned it for a easy transition for a new owner.\n\nWith over 200 sites, of which 169 are seasonal (separate meter), there is a strong base of business that provides certain revenue and profitability.\n\nHaving helped qualified buyers acquire dozens of campgrounds across Atlantic Canada, we&#039;ve identified many opportunities for improvement in revenues and we have discovered a unique aspect of this particular market that is driving new additional demand for seasonal campers.\n\nThe business operates from Victoria day until Thanksgiving. Given the strength of the seasonal nature of the business, it can be run with the support of just a few hands.\n\nThe sale is structured as a sale of 100% of the authorized and issued share capital of the company. For the purposes of this offering, the price considers Working Capital to be adjusted at $0. By completing the NDA and becoming a qualified buyer, we&#039;ll be happy to send you a full Offering Memorandum",
            "industry": "Real Estate",
            "price": "$2,799,000",
            "currency": "CAD",
            "created_timestamp": "1693236527",
            "created_datetime": "2023-08-28T11:28:47-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Confidential",
            "province": "NB",
            "country": "Canada",
            "location": "Confidential, NB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6354",
            "url": "https://buyandsellabusiness.com/business-opportunities/3608/beautiful-200-site-waterfront-campground-on-24-acres"
        },
        {
            "title": "Rural NB gas station for sale",
            "overview": "Located in Millville and close to the Crabbe Mountain ski resort (the location of the 2022 Canada Winter Games), this gas station property offers a lot of possibilities for an aspiring entrepreneur. Used to be a general store, the building used to host a kitchen, dining area, storage area, office and a 5 bedroom apartment in addition to the gas station retail space. \n\nWith a little TLC, this property can turn into an Air BnB serving the growing membership of the ski resort and the residents of the town of Millville.\n\nThe sale includes all the gas tank and the new pump, the property and all the equipment to run the gas station and all the furniture.",
            "industry": "Retail",
            "price": "$199,900",
            "currency": "CAD",
            "created_timestamp": "1693080078",
            "created_datetime": "2023-08-26T16:01:18-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Millville",
            "province": "NB",
            "country": "Canada",
            "location": "Millville, NB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6351",
            "url": "https://buyandsellabusiness.com/business-opportunities/3607/rural-nb-gas-station-for-sale"
        },
        {
            "title": "Successful Italian Franchise Restaurant in Fredericton, NB",
            "overview": "20 years in business and in a high traffic location, this business is everything you need if you are looking to become your own boss and also want to a work-life balance.",
            "industry": "Restaurant/Food Services",
            "price": "$300,000",
            "currency": "CAD",
            "created_timestamp": "1693079207",
            "created_datetime": "2023-08-26T15:46:47-04:00",
            "type": "Traditional",
            "operation": "Franchise",
            "city": "Fredericton",
            "province": "NB",
            "country": "Canada",
            "location": "Fredericton, NB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/restaurant-food-services.png",
            "url": "https://buyandsellabusiness.com/franchise-opportunities/3606/successful-italian-franchise-restaurant-in-fredericton-nb"
        },
        {
            "title": "Carpet &amp; Upholstery Cleaning Franchise For Sale",
            "overview": "Are you ready to step into the world of entrepreneurship and seize an opportunity in the lucrative cleaning industry? Look no further! We&#039;re offering an established Carpet and Upholstery Cleaning franchise for sale that&#039;s primed for success.\n\nWhat&#039;s Included:\nFully equipped and ready-to-go cleaning van\nHigh-quality cleaning supplies and equipment\nEstablished marketing materials and strategies\nBrand recognition and trust\nLarge Territory\n\nDon&#039;t miss out on this opportunity to be your own boss, set your own hours, and reap the rewards of your hard work. Take the first step towards financial independence and owning your own business.",
            "industry": "Consumer Services",
            "price": "$74,900",
            "currency": "CAD",
            "created_timestamp": "1692998365",
            "created_datetime": "2023-08-25T17:19:25-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Edmonton",
            "province": "AB",
            "country": "Canada",
            "location": "Edmonton, AB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6350",
            "url": "https://buyandsellabusiness.com/business-opportunities/3605/carpet-and-upholstery-cleaning-franchise-for-sale"
        },
        {
            "title": "Respected ice cream shop in downtown Toronto!",
            "overview": "Turnkey operation including all equipment &amp; recipes. Huge potential for expansion through additional locations, mobile cart, and a growing wholesale vegan line.\n\nHigh growth track record, high margin product, award winning recipes.\n\nLoyal and dedicated customers returning weekly 12 months of the year, several wholesale contracts with well-known grocers, and 15 corporate orders each year. Contacts and repeat orders from large corporations such as RBC, Intuit, Cushman &amp; Wakefield.\n\n4.5 years left on commercial lease with option to renew. Friendly and extremely helpful landlord. Great walk by traffic and accessible by TTC or car. Multiple high rise condos expected to be completed throughout the next few years with no competition in the area. No outstanding lease or finance payments on equipment.\n\nPassionate staff who are cross trained in each operation. We would also offer a training period for the new owner.\n\nWe can connect you with an accountant to assist with obtaining financing! He has a 100% success rate. We have a full business plan and valuation to assist with obtaining financing capital.\n\nWe are selling because we are starting a family and would like to move out of the city.",
            "industry": "Restaurant/Food Services",
            "price": "$565,000",
            "currency": "CAD",
            "created_timestamp": "1692924024",
            "created_datetime": "2023-08-24T20:40:24-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Toronto",
            "province": "ON",
            "country": "Canada",
            "location": "Toronto, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6347",
            "url": "https://buyandsellabusiness.com/business-opportunities/3604/respected-ice-cream-shop-in-downtown-toronto"
        },
        {
            "title": "20 year CRICOS RTO offering Cookery, Business, English and IT",
            "overview": "20  year history, check\nDesirable courses, check\nOperational team in place, check\n\nThis long-standing institution is in a remarkable position post COVID-19 for a savvy investor to take hold and drive it into 2024 and beyond. Starting at break even and nearly 400 remaining CRICOS places in the existing premises, a new owner will take advantage of having their operational expenses covered from day one with additional revenue contributing directly to profit.  \nThe college has never had any regulatory sanctions in its history and offers a fantastic location in the heart of Melbournes CBD. Both the campus and commercial kitchen locations are setup and approved by the regulator for delivery. \n\nThe scope on offer is as follows: \n\n- Hospitality \n- Information Technology\n- Business\n- Management\n- English\n\nThe above is approved by ASQA on both RTO and CRICOS registrations meaning you can continue delivering directly to international students on-shore in Melbourne. But you can diversify your customer base by branching out into the domestic market and apply for federal and state funding in the next round of applications.",
            "industry": "Education",
            "price": "$950,000",
            "currency": "AUD",
            "created_timestamp": "1692922064",
            "created_datetime": "2023-08-24T20:07:44-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Melbourne",
            "province": "VIC",
            "country": "Australia",
            "location": "Melbourne, VIC, Australia",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/education.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3603/20-year-cricos-rto-offering-cookery-business-english-and-it"
        },
        {
            "title": "Historic Bar/ Restaurant Downtown Barrie",
            "overview": "The Simcoe has been a staple of Downtown Barrie since 1876. This Business was recently re established in the original site (5 points Downtown Barrie) and includes the Business Name, a fresh 5 year lease at favorable rates in the historically protected building, Full Liquor License with caters endorsement, Full Kitchen with approval for walk up window to service walk ups and after bar crowd, Skip the dishes Uber Eats etc\n All supplier accounts with both Food and alcohol suppliers, skeleton crew staff (if you require them) on site training for new owners, and option to &quot;Contract Out&quot; the liquor license to the right qualified buyer\n\nWe specialize in re establishing and restructuring business for turn around.\nThis location was recently face lifted and improvements made, historic location with a historic following and daily improvising numbers with curated nights and kitchen traction.",
            "industry": "Restaurant/Food Services",
            "price": "$250,000",
            "currency": "CAD",
            "created_timestamp": "1692893723",
            "created_datetime": "2023-08-24T12:15:23-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Barrie",
            "province": "ON",
            "country": "Canada",
            "location": "Barrie, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/restaurant-food-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3602/historic-bar-restaurant-downtown-barrie"
        },
        {
            "title": "Established Fire Safety and Life Protection Company in Edmonton",
            "overview": "Are you interested in owning a successful fire safety and life protection company in Edmonton?  We present an established business boasting a robust portfolio of commercial clientele and a team of seasoned technicians dedicated to providing exceptional service.\n\nThis company boasts a track record of consistent profitability and substantial revenue growth within the fire safety and life protection sector. They have nurtured strong relationships with diverse commercial clients spanning Edmonton, Alberta, and Saskatchewan. Significant growth potential is readily accessible by broadening the geographic reach among the existing client base.\n\nRecognized for their unwavering commitment to customer satisfaction, the company offers round-the-clock emergency response services. Their comprehensive product and service offerings encompass fire alarm and sprinkler system installations and maintenance, as well as fire extinguisher recharging.\n\nWhether you&#039;re an ambitious entrepreneur or an established company seeking expansion opportunities within the fire safety domain, this represents a distinctive chance to acquire a respected and well-established business.",
            "industry": "Construction Services",
            "price": "$1,594,587",
            "currency": "CAD",
            "created_timestamp": "1692891214",
            "created_datetime": "2023-08-24T11:33:34-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Edmonton",
            "province": "AB",
            "country": "Canada",
            "location": "Edmonton, AB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6346",
            "url": "https://buyandsellabusiness.com/business-opportunities/3601/established-fire-safety-and-life-protection-company-in-edmonton"
        },
        {
            "title": "Turnkey Industrial Sales Company Bundled with Secondary Company",
            "overview": "Embark on a transformative journey with not just one, but two incredible businesses awaiting your ownership.\n\nThe first venture is a well-established Industrial Sales Company, renowned for its excellent reputation and wide-ranging clientele. This solid foundation ensures immediate success, spanning across crucial sectors like Welding, Industrial, Safety, and MRO (Maintenance, Repair, and Operations) supplies.\n\nBut that&#039;s not all  the second venture is an exciting Outdoor Living Company, tapping into the growing demand for enhanced outdoor experiences. This dual package allows you to diversify your portfolio, leverage your strengths, and drive innovation in two dynamic markets.\n\nWith all assets and inventory included in the sales price, these turnkey operations are ready for your ownership.",
            "industry": "Retail",
            "price": "$2,900,000",
            "currency": "CAD",
            "created_timestamp": "1692890671",
            "created_datetime": "2023-08-24T11:24:31-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Edmonton",
            "province": "AB",
            "country": "Canada",
            "location": "Edmonton, AB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6345",
            "url": "https://buyandsellabusiness.com/business-opportunities/3600/turnkey-industrial-sales-company-bundled-with-secondary-company"
        },
        {
            "title": "Premier Junk Removal Franchise",
            "overview": "Discover an unparalleled investment opportunity in the booming waste management industry. Become a part of a cutting-edge junk removal franchise that offers full-service solutions for both residential and commercial clients. Established in 2021, the franchise has swiftly risen to become a market leader, capitalizing on the growing demand for eco-friendly and efficient waste disposal solutions. The franchise model uniquely caters to both residential and commercial sectors, allowing franchisees to tap into multiple revenue streams. From homeowners to businesses, everyone seeks efficient and reliable waste removal services. Benefit from the strength of a nationally recognized brand. The company&#039;s marketing campaigns reach far and wide, driving business. This is an exclusive opportunity to get into an innovative junk removal franchise that&#039;s already reshaping the waste management landscape. If you&#039;re seeking a lucrative venture with a proven track record, get in touch with us today. Listing ID: 3564",
            "industry": "Cleaning Services",
            "price": "$1",
            "currency": "CAD",
            "created_timestamp": "1692810725",
            "created_datetime": "2023-08-23T13:12:05-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Home Based",
            "province": "ON",
            "country": "Canada",
            "location": "Home Based, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/cleaning-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3599/premier-junk-removal-franchise"
        },
        {
            "title": "Manufacturer of Custom Vinyl Products",
            "overview": "Are you looking for a profitable and reputable business opportunity in the vinyl products industry? Look no further than this well-established business with a 40-year history of excellence in manufacturing quality vinyl products. This company specializes in custom promotional products, binders, easel boards, boxes, envelopes, and more. With a loyal customer base and a fully-owned 10,000 sq ft facility, they are the exclusive manufacturer of their products on-site. With four decades of experience, this business has solidified its position in the vinyl products market, making it a trusted and respected brand. The business&#039;s specialty lies in creating tailor-made products, providing a competitive edge in the market and attracting customers seeking personalized solutions. All the manufacturing equipment is in excellent condition and is fully owned, ensuring a smooth and efficient production process. The current owner is looking to retire and is willing to train the new buyer, making it an ideal opportunity for those without prior experience in the industry. This is a turnkey business opportunity that offers a smooth transition to the right buyer. Listing ID: 3562",
            "industry": "Manufacturing",
            "price": "$425,000",
            "currency": "CAD",
            "created_timestamp": "1692810605",
            "created_datetime": "2023-08-23T13:10:05-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "GTA",
            "province": "ON",
            "country": "Canada",
            "location": "GTA, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/manufacturing.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3598/manufacturer-of-custom-vinyl-products"
        },
        {
            "title": "Profitable Composite Moulding Manufacturer",
            "overview": "With an unparalleled reputation in the industry, this esteemed company specializes in both interior and exterior composite moulding. With two decades of experience, they have been the preferred provider of high-quality architectural details to the global design and build community. One of the key reasons for their popularity is their ability to offer versatile yet economical alternatives, making them a sought-after choice in the building community. Their extensive range of offerings includes over 150 stock selections, custom products, and restoration services, making them the top choice for any architectural project. Situated in a convenient and easily accessible location just off the highway, their 14,400 sq ft facility serves as the manufacturing hub for their top-notch moulding products. With efficiency being a hallmark of their service, they offer competitive pricing, ensuring customer satisfaction and loyalty. Their reputation extends worldwide, earning the trust of professionals from all corners of the globe. Renowned designers have consistently relied on this company for their architectural needs. Listing ID: 3563",
            "industry": "Manufacturing",
            "price": "$800,000",
            "currency": "CAD",
            "created_timestamp": "1692810040",
            "created_datetime": "2023-08-23T13:00:40-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "GTA",
            "province": "ON",
            "country": "Canada",
            "location": "GTA, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/manufacturing.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3597/profitable-composite-moulding-manufacturer"
        },
        {
            "title": "Industrial and Commercial Electrical Contractors",
            "overview": "Enter a legacy of excellence with this well-established electrical contracting business. Having operated for four decades in the Industrial, Commercial, and Institutional sectors, this opportunity offers more than just a purchase; it&#039;s a chance to continue a legacy and build upon a firm foundation.\nExpertly staffed with a robust and skilled workforce, the company specializes in Power Systems, Lighting Systems, and more. The retiring owner guarantees a seamless transition, ready to pass on decades of industry wisdom and insight.\nImportantly, the business is primed for immediate success with numerous pre-signed projects and contracts. These include lucrative upcoming opportunities that ensure a steady revenue stream and continuous growth potential from day one. Additionally, the sale offers an option to acquire a valuable property priced at $2.5M CAD.\nThis unique opportunity is perfect for those ready to step into a leading role in the electrical services industry. Don&#039;t delay - seize this opportunity today!\nContact us today to learn more. Property also available at $2.5M CAD. Listing ID: 3499",
            "industry": "Repair/Maintenance Services",
            "price": "$1,300,000",
            "currency": "CAD",
            "created_timestamp": "1692809720",
            "created_datetime": "2023-08-23T12:55:20-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "GTA",
            "province": "ON",
            "country": "Canada",
            "location": "GTA, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/repair-maintenance-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3596/industrial-and-commercial-electrical-contractors"
        },
        {
            "title": "Successful Salesforce AI Consulting Business",
            "overview": "With an emphasis on data-driven solutions that leverage advanced BI and AI-powered technology, this rapidly growing Salesforce Consulting Partner has mastered Data Architecture and Predictive Analytics, boasting an astonishing 105% year-over-year growth from 2021 to 2022.\n\nHandpicked as one of just six global Einstein Expert Navigators by Salesforce thanks to their accomplishments in the AI space paired with a projected 53% growth rate from 2022 to 2023.\n\nA stellar CSAT score of 4.96/5 thanks to their signature Analytics Roadmap approach underlines this businesses commitment to delivering transformative projects and fostering lasting customer partnerships.\n\nAcknowledged as Subject Matter Experts by Salesforce, Tableau, Sales, and Solution Engineering teams, this Salesforce Consulting Partner possesses an organic pipeline of leads and is on track to become a Platinum/Summit (Top-Tier) partner by the end of the year and soon to be recognized as the only company globally with all three Expert Levels: Einstein, Managed Services, and Tableau. \n\nThe Founder is willing to stay on for an extended period of time to ensure a successful transition.",
            "industry": "Information Technology",
            "price": "$4,000,000",
            "currency": "USD",
            "created_timestamp": "1692737331",
            "created_datetime": "2023-08-22T16:48:51-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "San Francisco",
            "province": "CA",
            "country": "United States",
            "location": "San Francisco, CA, United States",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/information-technology.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3595/successful-salesforce-ai-consulting-business"
        },
        {
            "title": "Paving Business FOR SALE in GTA",
            "overview": "- Niche Business: Specializing in parking lot construction, the business has built strong connection with larger paving companies, and is the preeminent choice for larger contractors for its niche work.\n\n- Highly Profitable: The business has high profit margins with a revenue of $700K in YE 2022 and Seller&#039;s Discretionary Earnings of an impressive $400K for 2022.\n\n- Trustworthy Clientele: Regular, repeat business from larger contractors speaks to the businesss consistent quality.\n\n- Noteworthy work: Proudly constructed parking lots for one of Canada&#039;s largest retailers which leads to consistent workflow and a continual influx of service and maintenance projects.\n\n- Smooth Client Transition: The dedicated seller is committed to ensuring a seamless transition.\n\n- Valuable Assets: The business comes with approx. $280K worth of fully paid equipment, significantly adding to its value.\n\n- Seller Financing: Attractive financing options for eligible buyers, emphasizing the sellers belief in the business&#039;s sustainability.\n\n- Established Reputation: The work quality has cemented the businesss reputation as the go-to subcontractor for major paving companies.",
            "industry": "Construction Services",
            "price": "$799,000",
            "currency": "CAD",
            "created_timestamp": "1692639338",
            "created_datetime": "2023-08-21T13:35:38-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Greater Toronto Area",
            "province": "ON",
            "country": "Canada",
            "location": "Greater Toronto Area, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3594/paving-business-for-sale-in-gta"
        },
        {
            "title": "GingerFresh Indo Chinese",
            "overview": "GingerFresh Indo-Chinese - Delightful fusion celebrates cultural diversity and satisfies the modern appetite for innovative and unforgettable experiences.\n\nInnovative fusion of Indian and Chinese flavors creates a symphony of bold and harmonious tastes, offering a truly unforgettable dining experience that celebrates the best of two rich culinary traditions.",
            "industry": "Restaurant/Food Services",
            "price": "$285,000",
            "currency": "CAD",
            "created_timestamp": "1692472390",
            "created_datetime": "2023-08-19T15:13:10-04:00",
            "type": "Traditional",
            "operation": "Franchise",
            "city": "Calgary",
            "province": "AB",
            "country": "Canada",
            "location": "Calgary, AB, Canada",
            "thumbnail": "https://buyandsellabusiness.com/listing/image/6344",
            "url": "https://buyandsellabusiness.com/franchise-opportunities/3593/gingerfresh-indo-chinese"
        },
        {
            "title": "Electrical Contracting Business FOR SALE in Toronto",
            "overview": "- Very profitable electrical contracting business established for nearly 20 years\n\n- Company has a multi-year track record of profitability, average owner(s) discretionary earnings over past four years (incl. 2023 projection) is approximately $460K.\n\n- Average revenues over past four years (incl. 2023 projection) is approximately $3.3M\n\n- Business has a booked backlog of work of approximately $2M as of December 2022\n\n- Business had a downturn in 2022 due to COVID, however business is back on track in 2023 and projected to make $550k in owner(s) discretionary earnings and $3.9M in revenue as per the Seller\n\n- Business primarily provides electrical services in the commercial, industrial and telecommunication space and has become a market leader in its niche market of data centres, automation, industrial controls etc.\n\n- Benefits from repeat clientele and business relationships developed over many years in business that leads to ongoing revenues\n\n- Business has a unionized staff of 10 FT employees not including the two business owners and one office clerk\n\n- Both owner(s) key role is project management, estimating, overseeing operations, manage client relationships and staff",
            "industry": "Construction Services",
            "price": "$1,300,000",
            "currency": "CAD",
            "created_timestamp": "1692440432",
            "created_datetime": "2023-08-19T06:20:32-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Greater Toronto Area",
            "province": "ON",
            "country": "Canada",
            "location": "Greater Toronto Area, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3592/electrical-contracting-business-for-sale-in-toronto"
        },
        {
            "title": "General Contracting Business FOR SALE in Greater Kelowna Area",
            "overview": "- Very profitable general contracting business for sale, established near Kelowna in British Columbia for over 20 years\n\n- Company has a multi-year track record of profitability; average owner(s) discretionary earnings over past four years is approximately $1.05M.  Average revenues over past four years is approximately $5.7M\n\n- Business has a booked backlog of approximately $1.5M since January, 2023\n\n- Business primarily provides general contracting services for the construction of infrastructure facilities\n\n- Benefits from long-standing business relationships with owners and engineers over many years of business history that leads to regular ongoing revenue\n\n- Diversified client base with no single client leading to majority of business revenue every year\n\n- Business has a core staff of 10 F/T and 2 P/T staff not including the business owner\n\n- Business price includes approximately $900k of equipment, tools and inventory\n\n- The owners key role is to oversee operations, project management, estimating, manage client relationships and staff\n\n- The owner is looking to retire hence looking to sell the business but is willing to stay in a consulting capacity",
            "industry": "Construction Services",
            "price": "$3,980,000",
            "currency": "CAD",
            "created_timestamp": "1692440277",
            "created_datetime": "2023-08-19T06:17:57-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Greater Kelowna Area",
            "province": "BC",
            "country": "Canada",
            "location": "Greater Kelowna Area, BC, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3591/general-contracting-business-for-sale-in-greater-kelowna-area"
        },
        {
            "title": "General Contracting Business FOR SALE in Sudbury",
            "overview": "- Very profitable general contracting business established in the Sudbury area for over 30 years\n\n- Company has a multi-year track record of profitability; average owners discretionary earnings including past two years and current year projections is approximately $990k and average revenue is approximately $8.9M\n\n- Business has a booked backlog of approximately $5M as of April, 2023\n\n- Business primarily provides general contracting services for commercial buildings including new builds, renovations and additions\n\n- Benefits from long-standing business relationships with local owners, architects and engineers over many years of business history that leads to regular ongoing revenue\n\n- Business has exclusive rights to products for a pre-engineered metal building manufacturer (more details to be provided after NDA is signed)\n\n- Business has a core staff of 9 F/T field staff and 2 F/T office staff, not including the business owners\n\n- The owners key role is to oversee operations, project management, estimating, manage client relationships and staff\n\n- The owners are looking to retire hence looking to sell the business but is willing to stay in a consulting capacity",
            "industry": "Construction Services",
            "price": "$1,850,000",
            "currency": "CAD",
            "created_timestamp": "1692439719",
            "created_datetime": "2023-08-19T06:08:39-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Greater Sudbury Area",
            "province": "ON",
            "country": "Canada",
            "location": "Greater Sudbury Area, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3590/general-contracting-business-for-sale-in-sudbury"
        },
        {
            "title": "Custom Cabinetry Business FOR SALE in Toronto",
            "overview": "- Profitable full-service custom cabinetry manufacturing and installation located in GTA\n\n- Established for more than 30 years\n\n- Core products include custom residential cabinetry i.e kitchen, bathroom, wall units and mud-rooms\n\n- Revenue of $630k and owner discretionary income of $261K in fiscal YE 2021\n\n- Strong customer base and reputation\n\n- Provides great customer service to its clients and has become go-to custom cabinetry company for homeowners, builders and renovators of high-end properties in its niche market\n\n- Business has earned many five-star reviews and ratings on third-party websites like Google, Facebook etc. \n\n- Staff of 2 FT and 1PT non-union employees plus the owner\n\n- Business is owned by 1 owner whom is looking to retire. However, is willing to stay on as a consultant for a negotiable amount of time.",
            "industry": "Construction Services",
            "price": "$598,000",
            "currency": "CAD",
            "created_timestamp": "1692439577",
            "created_datetime": "2023-08-19T06:06:17-04:00",
            "type": "Traditional",
            "operation": "Independent",
            "city": "Toronto",
            "province": "ON",
            "country": "Canada",
            "location": "Toronto, ON, Canada",
            "thumbnail": "https://buyandsellabusiness.com/dashboard/img/industries/construction-services.png",
            "url": "https://buyandsellabusiness.com/business-opportunities/3589/custom-cabinetry-business-for-sale-in-toronto"
        }
]

# Create a DataFrame from the array
df = pd.DataFrame(data[1:], columns=data[0])

# Define the Excel file path
excel_file = 'Products.xlsx'

# Write the DataFrame to an Excel sheet
df.to_excel(excel_file, index=False)
